accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),

]

app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView,SubmitAnswer,TreasureHuntView	

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),
    path('quiz/', TreasureHuntView.as_view(), name='quiz'),

    path('submit/', SubmitAnswer, name='submitAnswer'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/templates/layouts/default/page.html
{% load staticfiles %}
{% load bootstrap4 %}
{% load i18n %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>

    <meta charset="utf-8">

<!-- scripts -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A Treasure hunt portal.">
    <meta name="author" content="Harsh Srivastava">

    <link rel="icon" href="{% static 'favicon.jpg' %}">

    <title>Treasure Hunt</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">




    <style type="text/css">
        body {
            width: 100wh;
            height: 90vh;
            background: linear-gradient(-45deg, #EE7752, #E73C7E, #23A6D5, #23D5AB);
            background-size: 400% 400%;
            -webkit-animation: Gradient 15s ease infinite;
            -moz-animation: Gradient 15s ease infinite;
            animation: Gradient 15s ease infinite;
          }

          @-webkit-keyframes Gradient {
            0% {
              background-position: 0% 50%
            }
            50% {
              background-position: 100% 50%
            }
            100% {
              background-position: 0% 50%
            }
          }

          @-moz-keyframes Gradient {
            0% {
              background-position: 0% 50%
            }
            50% {
              background-position: 100% 50%
            }
            100% {
              background-position: 0% 50%
            }
          }

          @keyframes Gradient {
            0% {
              background-position: 0% 50%
            }
            50% {
              background-position: 100% 50%
            }
            100% {
              background-position: 0% 50%
            }
          }

          h1,
          h6 {
            font-family: 'Open Sans';
            font-weight: 300;
            text-align: center;
            position: absolute;
            top: 45%;
            right: 0;
            left: 0;
          }
        .login {
          overflow: hidden;
          background-color: white;
          padding: 40px 30px 30px 30px;
          border-radius: 10px;
          width: 400px;
          -webkit-transform: translate(-50%, -50%);
          -moz-transform: translate(-50%, -50%);
          -ms-transform: translate(-50%, -50%);
          -o-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
          -webkit-transition: -webkit-transform 300ms, box-shadow 300ms;
          -moz-transition: -moz-transform 300ms, box-shadow 300ms;
          transition: transform 300ms, box-shadow 300ms;
          box-shadow: 5px 10px 10px rgba(2, 128, 144, 0.2);
        }
        .login::before, .login::after {
          content: '';
          position: absolute;
          width: 600px;
          height: 600px;
          border-top-left-radius: 40%;
          border-top-right-radius: 45%;
          border-bottom-left-radius: 35%;
          border-bottom-right-radius: 40%;
          z-index: -1;
        }
        .login::before {
          left: 40%;
          bottom: -130%;
          background-color: rgba(69, 105, 144, 0.15);
          -webkit-animation: wawes 6s infinite linear;
          -moz-animation: wawes 6s infinite linear;
          animation: wawes 6s infinite linear;
        }
        .login::after {
          left: 35%;
          bottom: -125%;
          background-color: rgba(2, 128, 144, 0.2);
          -webkit-animation: wawes 7s infinite;
          -moz-animation: wawes 7s infinite;
          animation: wawes 7s infinite;
        }
        .login > input {
          font-family: "Asap", sans-serif;
          display: block;
          border-radius: 5px;
          font-size: 16px;
          background: white;
          width: 100%;
          border: 0;
          padding: 10px 10px;
          margin: 15px -10px;
        }
        .login > button {
          font-family: "Asap", sans-serif;
          cursor: pointer;
          color: #fff;
          font-size: 16px;
          text-transform: uppercase;
          width: 80px;
          border: 0;
          padding: 10px 0;
          margin-top: 10px;
          margin-left: -5px;
          border-radius: 5px;
          background-color: #f45b69;
          -webkit-transition: background-color 300ms;
          -moz-transition: background-color 300ms;
          transition: background-color 300ms;
        }
        .login > button:hover {
          background-color: #f24353;
        }

        @-webkit-keyframes wawes {
          from {
            -webkit-transform: rotate(0);
          }
          to {
            -webkit-transform: rotate(360deg);
          }
        }
        @-moz-keyframes wawes {
          from {
            -moz-transform: rotate(0);
          }
          to {
            -moz-transform: rotate(360deg);
          }
        }
        @keyframes wawes {
          from {
            -webkit-transform: rotate(0);
            -moz-transform: rotate(0);
            -ms-transform: rotate(0);
            -o-transform: rotate(0);
            transform: rotate(0);
          }
          to {
            -webkit-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -ms-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
          }
        }

    </style>
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="/">{% trans 'Home' %}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/quiz/"><strong>{% trans 'Treasure Hunt' %}</strong></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_password' %}">{% trans 'Change password' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_profile' %}">{% trans 'Change profile' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_email' %}">{% trans 'Change email' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:sign_up' %}">{% trans 'Create an account' %}</a>
                </li>
            {% endif %}
        </ul>

<!--         <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'change_language' %}">{% trans 'Change language' %}</a>
            </li>
        </ul>
 -->    </div>

</nav>

<div class="container-fluid mt-3" style="padding:25px;">

    {% bootstrap_messages %}

    {% block content %}
        No content.
    {% endblock %}

</div>

<script src="{% static 'vendor/jquery/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>